### PR TITLE
Add support for reading list of target urls from a file

### LINKED ISSUE #50: @file for url option?
Hey!

I was wondering if its possible to use @ to include a file with urls in the url option?
Want to run this on a list of random urls (in the same web application) to loadtest (like -f in siege).

### PR DESCRIPTION
**Pull request by richardmarshall**
When the test target string starts with an '@' it will be interpreted as a
file path to load a list of URLs.

Resolves #50

### CODE REVIEW

**Comment by richardmarshall** [comment]
We've been testing out this mechanism for a few weeks internally and it worked out well for us.

**Comment by wmorgan** [comment]
@richardmarshall thanks! Would you mind signing the CLA at https://buoyant.io/cla/ ?

**Comment by richardmarshall** [comment]
@wmorgan Yeah, I'll work on getting that sorted out.

**Comment by richardmarshall** [comment]
CLA is being reviewed by our legal team now.

**Comment by richardmarshall** [comment]
@wmorgan Do you have a legal contact I can forward some comments to from our legal team regarding the CLA?

**Comment by wmorgan** [comment]
@richardmarshall you can send those to me (william at buoyant dot io) and I'll forward them as appropriate. Thanks!

**Comment by richardmarshall** [comment]
Thanks, will do

**Comment by richardmarshall** [comment]
@wmorgan Just wanted to check in and see if you've received the doc file from our legal folks.

**Comment by ahume** [comment]
Would be great to see this picked up again.

**Comment by wmorgan** [comment]
@richardmarshall I did receive the doc, but we decided it wasn't feasible to maintain unique CLAs for contributors. Sorry for not updating this ticket to reflect that.

However, we've moved to a DCO approach in this repo (and the Linkerd repos), which lowers the burden on you substantially. Take a look at the DCO file in this repo, and if you agree with what it says, a `git commit --amend -s` will add a signoff to your commit. Then we can merge this.

**Comment by richardmarshall** [comment]
@wmorgan No worries.

Rebased by branch, resolved the conflicts, and added the signoff.

**Pull request merged**
