### PR TITLE
Add flag to set request body payload

### PR DESCRIPTION
**Pull request by richardmarshall**
Enable setting of the HTTP request body data either from a string passed
directly to the `-data` flag, a file, or stdin.

### CODE REVIEW

**Comment by stevej** [comment]
Sorry for the long delay (holidays, etc). I like this change, could you fix the conflicts and I'll give it a thumbs up.

**Comment by richardmarshall** [comment]
No worries. Rebased on current master.

**Comment by klingerf** [comment]
On the other hand, it looks like curl uses "@-" to read from stdin, which is the same convention used in this branch. In that case, you can disregard my earlier comment.

**Comment by richardmarshall** [comment]
Yeah, that was intended. I based the behavior on curl.

**Comment by klingerf** [comment]
Thanks @richardmarshall!

**Pull request merged**
